# Generated by Django 3.1.2 on 2020-10-14 10:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import leaves.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplierApprover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appliers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, validators=[leaves.models.date_validate])),
                ('date_applied', models.DateField(auto_now=True)),
                ('reason', models.CharField(max_length=50)),
                ('rejection_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=10)),
                ('applier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applier_leaves', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approver_leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('applier', 'date')},
            },
        ),
    ]
