# Generated by Django 3.1.2 on 2020-10-14 10:13

from django.db import migrations
from users.permissions import create_user_groups_permissions

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
         migrations.RunPython(create_user_groups_permissions)
    ]
